- content/_index.md
redirect to https://navcoin.org/wallets/ does not seem to work
> fix download link on index page under "its easy to use"

- themes/nav-community-v1/layouts/partials/head.html
> Added site verification

- themes/nav-community-v1/layouts/partials/head.html
So that Google Analytics can fire
> Removed hugoenv tag

- content/downloads/index.md
- themes/nav-community-v1/layouts/shortcodes/box_links_section_two.html
Last section on this page:
https://deploy-preview-24--objective-montalcini-de8891.netlify.com/downloads/
> added coinomi iOS. Fixed 2 box layout

- themes/nav-community-v1/layouts/news/list.html
- themes/nav-community-v1/layouts/news/single.html
- themes/nav-community-v1/layouts/notice_categories/list.html
- themes/nav-community-v1/layouts/notices/list.html
- themes/nav-community-v1/layouts/notices/single.html
- themes/nav-community-v1/layouts/npip_categories/list.html
- themes/nav-community-v1/layouts/npips/list.html
- themes/nav-community-v1/layouts/npips/single.html
- themes/nav-community-v1/layouts/partials/header.html
- themes/nav-community-v1/layouts/partials/header_three.html
- themes/nav-community-v1/layouts/partials/header_three_title.html
- themes/nav-community-v1/layouts/partials/header_two.html
Only way to build successfully when running `hugo server`
Thought this may resolve the build issue. maybe?
> Fix build issue: Use partial instead of template 

- content/notices/2018-10-24-navcoin-core-4-4-0.md
Updates the article with download links and info about the version bit trejectiosn
> 4.4.0 changes

- content/roadmap/cold-staking.en.md
- content/roadmap/cold-staking.es.md
- content/roadmap/static-block-reward.en.md
fixes broken npip links to for static rewards and coldstaking
> fixes broken links in roadmap

- content/roadmap/cold-staking.en.md
- content/roadmap/cold-staking.es.md
- content/roadmap/community-fund.en.md
- content/roadmap/community-fund.es.md
- content/roadmap/increase-cf-contrib.en.md
- content/roadmap/increase-cf-contrib.es.md
- content/roadmap/open-alias.en.md
- content/roadmap/open-alias.es.md
- content/roadmap/static-block-reward.en.md
- content/wallets/index.en.md
- content/wallets/index.es.md
- themes/nav-community-v2/layouts/roadmap/list.html
- themes/nav-community-v2/layouts/roadmap/single.html
the links are not working, but it's uploaded to github, it will be ready to merge
> update donwload page to 4.5.0

- content/why-navcoin/index.en.md
Only merge after 4.5.0 released
> Update cold staking mention

- themes/nav-community-v2/layouts/notice_categories/list.html
- themes/nav-community-v2/layouts/notices/list.html
Fixes #134
Preview: https://deploy-preview-135--navcoin.netlify.com/en/notices
> Fixed broken sidebar links

- content/privacy-policy/index.it.md
Italian translation for Privacy Policy
> privacy-policy/index.it.md - ITALIAN

- content/_index.en.html
- content/_index.es.html
- content/_index.jp.html
- content/_index.kr.html
- content/_index.ru.html
- content/_index.zh.html
Fixed the home page templates so they render correctly on version 3+ of hugo by adding frontmatter sections to the top.
Fixed #207 
run the server locally and browse to: http://localhost:1313/en/
netlify preview: https://deploy-preview-208--navcoin.netlify.com/en/
> front matter added to index pages

- themes/nav-community-v2/static/css/nav.scss
- themes/nav-community-v2/static/css/wallet.scss
fixed wallet icons being squished
> fixed wallet icons being squished

- themes/nav-community-v2/static/css/feature.scss
- themes/nav-community-v2/static/css/long-text.scss
> center aligned titles

- content/why-navcoin/index.en.md
- content/why-navcoin/index.es.md
- content/why-navcoin/index.it.md
- content/why-navcoin/index.jp.md
- content/why-navcoin/index.kr.md
- content/why-navcoin/index.ru.md
- content/why-navcoin/index.zh.md
- themes/nav-community-v2/static/assets/NavCoinOverview_September2019.pdf
Updated Overview PDF to include Magnum Wallet & some other options (coinomi, navpaper).
Juguelio Request.
https://deploy-preview-249--navcoin.netlify.com/en/why-navcoin
> updated PDF

- content/wallets/index.en.md
- content/wallets/index.es.md
- content/wallets/index.it.md
- content/wallets/index.jp.md
- content/wallets/index.kr.md
- content/wallets/index.ru.md
- content/wallets/index.zh.md
NavPi is no longer supported.
resolves #274
https://deploy-preview-275--navcoin.netlify.com/en/wallets
https://deploy-preview-275--navcoin.netlify.com/es/wallets
https://deploy-preview-275--navcoin.netlify.com/jp/wallets
https://deploy-preview-275--navcoin.netlify.com/it/wallets
https://deploy-preview-275--navcoin.netlify.com/kr/wallets
https://deploy-preview-275--navcoin.netlify.com/ru/wallets
https://deploy-preview-275--navcoin.netlify.com/zh/wallets
> Remove NavPi from wallets.

- content/notices/2021-01-15-navcoin-core-6-0-0.md
- content/wallets/index.en.md
- content/wallets/index.es.md
- content/wallets/index.it.md
- content/wallets/index.jp.md
- content/wallets/index.kr.md
- content/wallets/index.ru.md
- content/wallets/index.zh.md
> Navcoin core 6.0.0 release

- content/community-fund/index.en.md
- content/community-fund/index.it.md
- content/community-fund/index.jp.md
- content/community-fund/index.kr.md
- content/community-fund/index.ru.md
- content/community-fund/index.zh.md
> Update communityfund.nav.community links

- content/buy-navcoin/index.en.md
- content/buy-navcoin/index.es.md
- content/buy-navcoin/index.it.md
- content/buy-navcoin/index.jp.md
- content/buy-navcoin/index.kr.md
- content/buy-navcoin/index.ru.md
- content/buy-navcoin/index.zh.md
Fix broken links from buy-navcoin page.
https://github.com/navcoin/navcoin-org/issues/297
https://deploy-preview-299--navcoin.netlify.app/en/buy-navcoin
> removes broken links (buy-navcoin)

- content/notices/2021-02-18-navcoin-core-6-0-1.md
- content/wallets/index.en.md
- content/wallets/index.es.md
- content/wallets/index.it.md
- content/wallets/index.jp.md
- content/wallets/index.kr.md
- content/wallets/index.ru.md
- content/wallets/index.zh.md
> Navcoin Core 6.0.1 release

- config.toml
- themes/nav-community-v2/layouts/partials/header_menu.html
add knowledge base to the navigation menu
https://github.com/navcoin/navcoin-org/issues/298
https://deploy-preview-302--navcoin.netlify.com/es/
> add knowledge base to the navigation menu

- content/privacy-policy/index.en.md
> Update privacy policy

- content/notices/2021-02-21-navcoin-core-602.md
- content/wallets/index.en.md
- content/wallets/index.es.md
- content/wallets/index.it.md
- content/wallets/index.jp.md
- content/wallets/index.ru.md
- content/wallets/index.zh.md
There was error in date format. Fixed and updated NavCoin to Navcoin.
> Fix 602notice not rendering

- content/wallets/index.en.md
- content/wallets/index.es.md
- content/wallets/index.it.md
- content/wallets/index.jp.md
- content/wallets/index.kr.md
- content/wallets/index.ru.md
- content/wallets/index.zh.md
Magnum wallet platform has stopped its all services including Navcoin.
eg.
https://deploy-preview-306--navcoin.netlify.com/en/wallets
https://deploy-preview-306--navcoin.netlify.com/es/wallets
https://deploy-preview-306--navcoin.netlify.com/it/wallets
https://deploy-preview-306--navcoin.netlify.com/jp/wallets
https://deploy-preview-306--navcoin.netlify.com/kr/wallets
https://deploy-preview-306--navcoin.netlify.com/ru/wallets
https://deploy-preview-306--navcoin.netlify.com/zh/wallets
The preview can be found on the pull request once it's made by clicking `show all checks` > `details`.
> Remove magnum wallet

- content/buy-navcoin/index.en.md
- content/buy-navcoin/index.es.md
- content/buy-navcoin/index.it.md
- content/buy-navcoin/index.jp.md
- content/buy-navcoin/index.kr.md
- content/buy-navcoin/index.ru.md
- content/buy-navcoin/index.zh.md
> Buynavcoin exchanges updated - issue #309

- content/wallets/index.en.md
- content/wallets/index.es.md
- content/wallets/index.it.md
- content/wallets/index.jp.md
- content/wallets/index.kr.md
- content/wallets/index.ru.md
- content/wallets/index.zh.md
> Remove navpay

- netlify.toml
adds netlify configuration to prevent xss and clickjacking
> add xss and iframe prevention headers

- content/_index.en.html
- content/_index.es.html
- content/_index.it.html
- content/_index.jp.html
- content/_index.kr.html
- content/_index.ru.html
- content/_index.zh.html
- content/bounties/index.en.md
- content/bounties/index.es.md
- content/bounties/index.it.md
- content/bounties/index.jp.md
- content/bounties/index.kr.md
- content/bounties/index.ru.md
- content/bounties/index.zh.md
- content/community-fund/index.en.md
- content/community-fund/index.it.md
- content/community-fund/index.jp.md
- content/community-fund/index.kr.md
- content/community-fund/index.ru.md
- content/community-fund/index.zh.md
- content/responsible-disclosure/index.en.md
- content/responsible-disclosure/index.es.md
- content/responsible-disclosure/index.it.md
- content/responsible-disclosure/index.jp.md
- content/responsible-disclosure/index.kr.md
- content/responsible-disclosure/index.ru.md
- content/responsible-disclosure/index.zh.md
as per disclosure report recommendation
> nofollow noopener noreferrer rel tag added to all target _blank links

- content/notices/2021-05-06-navcoin-core-610.md
- content/wallets/index.en.md
- content/wallets/index.es.md
- content/wallets/index.it.md
- content/wallets/index.jp.md
- content/wallets/index.kr.md
- content/wallets/index.ru.md
- content/wallets/index.zh.md
> Navcoin Core 6.1.0

- static/js/bounties.js
- static/js/developers.js
- static/js/exchanges.js
- static/js/index.js
- static/js/support.js
> Formatting cleanup

- static/data/exchanges.json
Remove HitBTC.
Removed HitBTC from `exchanges.json`.
[Link to preview](https://deploy-preview-344--navcoin.netlify.app).
> Removed HitBTC

- content/get-started.html
Wait for merging until 7.0 release.
> Navcoin Core 7.0

- content/roadmap.html
Update roadmap to reflect the release of Navcoin Core 7.0.0.
- Move `MCL Library Integration` and `Boost Library Cleanup` to `Completed`
- Set `Social Mining Platform` to 75% (should be moved to `Completed` when out of beta)
- Set `Burn Transaction Fees`, `Burn Transaction Fees` and `Improvements to xNAV` to 75% (should be moved to `Completed` when/if soft fork activates)
- Set `Private Tokens`, `Private NFTs`, `dotNAV` and `On-Chain Trading Protocol` to 75% (should be moved to `Completed` when/if binding consultation vote passes in Q1 2022)
[Link to preview](https://deploy-preview-339--navcoin.netlify.app/roadmap)
> Update roadmap to reflect the release of Navcoin Core 7.0.0

- content/404.html
- content/assets.html
- content/bounties.html
- content/developers.html
- content/ecosystem.html
- content/exchanges.html
- content/get-started.html
- content/grants.html
- content/index.html
- content/privacy-policy.html
- content/responsible-disclosure.html
- content/roadmap.html
- content/support.html
- content/terms-of-use.html
Add footer link for the social hub.
Added the footer link under `Community` as `Social Hub`.
[Link to preview](https://deploy-preview-349--navcoin.netlify.app)
> Add footer link for the social hub

- content/get-started.html
updating full node download link from 7.0.0 to 7.0.1
> update full node url

- content/assets.html
Update reference to logos on `/assets` page.
[Link to preview](https://deploy-preview-361--cranky-visvesvaraya-877402.netlify.app/assets)
> Add platform section about private tokens and NFTs

- content/get-started.html
Added links to the exchanges icons on /get-started page
https://deploy-preview-366--cranky-visvesvaraya-877402.netlify.app/get-started
> Added links to the exchanges icons on /get-started page

- static/data/exchanges.json
Remove coinmerce, coinswitch, move Bitrue up
eg. https://deploy-preview-205--navcoin.netlify.com/en/buy-navcoin
The preview can be found on the pull request once it's made by clicking `show all checks` > `details`.
> remove-coinmerce-and-coinswitch

- content/404.html
- content/assets.html
- content/bounties.html
- content/developers.html
- content/ecosystem.html
- content/exchanges.html
- content/get-started.html
- content/grants.html
- content/index.html
- content/privacy-policy.html
- content/responsible-disclosure.html
- content/roadmap.html
- content/support.html
- content/terms-of-use.html
- static/js/google-tag-manager-body.js
- static/js/google-tag-manager-head.js
> Remove GTM analytics
